### ISSUE TITLE
Supporting additional Interfaces.

### ISSUE THREAD

**Issue by OutOfThisPlanet** [macvk/dnsleaktest#14]
I required the ability to check for DNS leaks on multiple network interfaces, so I edited your script.

**Added the following variable a the beginning:** 

`interface='enp1s0u1u3'`

**Changed the following lines:** 

`curl --silent --head --request GET "https://${api_domain}" | grep "200 OK" > /dev/null`

`result_json=$(curl --silent "https://${api_domain}/dnsleak/test/${id}?json")`

`result_txt=$(curl --silent "https://${api_domain}/dnsleak/test/${id}?txt")`

**to:** 

`curl --silent --head --interface ${interface}  --request GET "https://${api_domain}" | grep "200 OK" > /dev/null`

`result_json=$(curl --silent --interface ${interface} "https://${api_domain}/dnsleak/test/${id}?json")`

`result_txt=$(curl --silent --interface ${interface} "https://${api_domain}/dnsleak/test/${id}?txt")`

Perhaps this could be something you could more elegantly solve in a future release? :)

Good work bud!

**Comment by macvk** [comment]
The script was fixed, pls check latest version [https://raw.githubusercontent.com/macvk/dnsleaktest/master/dnsleaktest.sh](https://raw.githubusercontent.com/macvk/dnsleaktest/master/dnsleaktest.sh)
Use -i option to change the interface
`./dnsleaktest -i eth1`
