### ISSUE TITLE
Potential collision due to random number

### ISSUE THREAD

**Issue by dnlldl** [macvk/dnsleaktest#18]
Context: https://community.cloudflare.com/t/question-about-very-rare-dns-leak/589872/8

There is currently nothing preventing a collision if 2 requests were to be made with the same random number at nearly the same time.

**Comment by macvk** [comment]
I've made the corresponding changes. You can use centralized ID generator available here [https://bash.ws/id](https://bash.ws/id) to get unique IDs. 

PS. Yes, it is possible to get the same number from 1,000,000. The probability of the event to get the same number from the 1,000,000 is 10^(-12). I think this near enough to zero. The same approach is used by Microsoft for GUID generation. There is no centralized "generator" for GUIDs.

**Comment by dnlldl** [comment]
> I've made the corresponding changes. Please check it. You can use centralized ID generator available here https://bash.ws/id to get 100% unique IDs. ID is now 16 bytes long and includes 'a'...'z' characters, so it is 16^36 combinations. The web site ensures the IDs are unique (as an additional validation).

Thank you, just updated my script!

> PS. The old approach will also work. And yes, it is possible to get the same number from 1,000,000. The probability of the event to get the same number from the 1,000,000 is 10^(-12). I think this near enough to zero. The same approach is used by Microsoft for GUID generation. There is no centralized "generator" for GUIDs.

Do you keep stats on how many requests are made? And are the IDs valid for some time before being reset? With scripting it can go quite fast, I understand 1/1M doesn't seem a lot, but this is the birthday paradox. I don't think it's as simple as 10^(-12).

https://en.wikipedia.org/wiki/Birthday_problem
https://www.scientificamerican.com/article/bring-science-home-probability-birthday-paradox/
