### ISSUE TITLE
bash.ws domain expired

### ISSUE THREAD

**Issue by dnlldl** [macvk/dnsleaktest#21]
The script can't work since the API is not available anymore.
https://www.whois.com/whois/bash.ws

**Comment by macvk** [comment]
thanks for pointing it out. My apologies. It's fixed now

**Comment by dnlldl** [comment]
> thanks for pointing it out. My apologies. It's fixed now

Thank you very much!

I can't help but wonder if you'd be open to make the whole thing open-source (unless it is already without me realizing) so that someone else could continue/improve the project if for any reason you can't renew the domain or continue to host the website/API.
