### ISSUE TITLE
Not Working in Windows 10

### ISSUE THREAD

**Issue by zuchie-star** [macvk/dnsleaktest#9]
This Doesn't seem to be working in windows 10

**Comment by macvk** [comment]
More details please, what error do you see? What script did you run?
I run the scripts quite often and don't face any error as for now.

**Comment by zuchie-star** [comment]
Hi, thanks for the swift reply.

I down load the .bat file, then I run the bat and I get a blank cmd screen.

Running on windows 10

Cheers

On 16 Jul 2021, at 4:48 pm, macvk ***@***.***> wrote:

﻿

More details please, what error do you see? What script did you run?
I run the scripts quite often and don't face any error as for now.

**Comment by macvk** [comment]
Understood. You run the script from explorer, but this is the console scripts. You should run the cmd.exe first. 
Click "Start", then type "cmd" (without quotes), then hit Enter. A console will appear. 
Then you should change current directory to the directory where dnsleaktest.bat is located and run dnsleaktest.bat.
cd %USERPROFILE%\downloads
dnsleaktest.bat

OR add to the of the script command "pause".

**Comment by zuchie-star** [comment]
Ahh the old change directory chestnut. It’s all working now.

Thank you for your swift replies and help.

Have a good one

On 16 Jul 2021, at 5:28 pm, macvk ***@***.***> wrote:

﻿

Understood. You run the script from explorer, but this is the console scripts. You should run the cmd.exe first.
Click "Start", then type "cmd" (without quotes), then hit Enter. A console will appear.
Then you should change current directory to the directory where dnsleaktest.bat is located and run dnsleaktest.bat.
cd %USERPROFILE%\downloads
dnsleaktest.bat

OR add to the of the script command "pause".
